packages:
  - ./
  - .playground/

catalogs:
  cli:
    "@antfu/eslint-config": ^6.2.0
    "@antfu/ni": ^27.0.1
    bumpp: ^10.3.1
    eslint: ^9.39.1
    tsdown: ^0.16.0
    typescript: ^5.9.3
    vite: ^7.2.1
  inlined:
    "@antfu/utils": ^9.3.0
  peer:
    nuxt: ^3.0.0
    vue: ^3.0.0
  playground:
    nuxt: ^4.2.1
    vue: ^3.5.25
    vue-router: ^4.6.3
  types:
    "@types/node": ^24.10.0

ignoreWorkspaceRootCheck: true

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild

shellEmulator: true
